# Sub-Episode B for Episodes 16-30. Flags: G=Gala, S=Ethylene, A=Aila, D=Dhruva
from b_s1 import sub

B2 = {
16: sub(16, "Lorong-Lorong Beku",
 "Patroli di Kegelapan", [
 ("16B.1a", "Wide Shot", "Lorong beku panjang; robot patroli biru berbaris melewati persimpangan.", "A long frozen corridor inside the fortress: blue-eyed patrol robots march past a junction in single file.", ""),
 ("16B.1b", "Medium Shot", "Regu merapat ke dinding es dalam bayangan; Gala meredupkan Ethylene dengan telapak tangan.", "The squad presses flat against an icy wall in shadow; Gala cups a hand over the sprite to dim its glow.", "GSAD"),
 ("16B.1c", "Close-Up", "Sirip angin di pergelangan Aila berdengung, membelokkan suara langkah mereka.", "Close-up: the wind fins on Aila's wrists hum softly as she bends a thin air current to carry their footsteps away.", "A"),
 ("16B.1d", "Medium Shot", "Patroli berlalu; Dhruva menghela napas lega.", "The patrol passes by; Dhruva lets out a long, quiet breath of relief.", "D"),
 ],
 "Terminal Peta", [
 ("16B.2a", "Medium Shot", "Aila menyambungkan kabel visor ke terminal dinding yang berlapis es.", "Aila connects a thin cable from her visor to an ice-crusted wall terminal.", "A"),
 ("16B.2b", "First-Person POV (HUD)", "HUD: peta 3D benteng; jalur tercepat lewat 'MAINTENANCE PASSAGE'.", "First-person HUD: a 3D fortress map with the generator deep below and the shortest route marked 'MAINTENANCE PASSAGE'.", ""),
 ("16B.2c", "Medium Shot", "Gala menunjuk lorong itu; Dhruva mengernyit curiga.", "Gala points down the passage on the map while Dhruva frowns uneasily.", "GD"),
 ("16B.2d", "Wide Shot", "Regu memasuki lorong logam bersih yang terlalu sunyi.", "The squad steps into a long, spotless metal hallway that is far too quiet.", "GAD"),
 ]),
17: sub(17, "Harga Sebuah Jebakan",
 "Rekan yang Terkuras", [
 ("17B.1a", "Medium Shot", "Aila dan Dhruva berlutut; lampu zirah mereka meredup, napas berembun.", "Aila and Dhruva kneel in the wrecked chamber, their armor lights dimmed, breath fogging in the cold.", "AD"),
 ("17B.1b", "Close-Up", "Gala menempelkan gauntlet bercahaya ke bahu Dhruva, mengalirkan hangat.", "Close-up: Gala rests a glowing gauntlet on Dhruva's shoulder plate, warmth flowing into it.", "GD"),
 ("17B.1c", "Close-Up", "Ethylene menempel di visor Aila; visor menyala kembali.", "Close-up: the sprite nuzzles against Aila's visor and it flickers back to full teal light.", "AS"),
 ("17B.1d", "Medium Shot", "Regu berdiri lagi dengan tekad.", "The squad rises to its feet again, determined.", "GAD"),
 ],
 "Turun ke Lapisan Terdalam", [
 ("17B.2a", "Wide Shot", "Lift barang turun ke poros beku.", "A freight elevator carries the squad down a deep frozen shaft, blue lights sliding past.", "GAD"),
 ("17B.2b", "First-Person POV (HUD)", "HUD: suhu anjlok '-40°C ... -72°C ... -100°C'.", "First-person HUD temperature readout plunging: '-40°C ... -72°C ... -100°C'.", ""),
 ("17B.2c", "Close-Up", "Bunga es merambati kaca lift.", "Close-up: fractal frost blooms across the elevator's small window.", ""),
 ("17B.2d", "Medium Shot", "Pintu lift terbuka ke kabut putih pekat.", "The elevator doors slide open onto a wall of thick white freezing fog.", "GAD"),
 ]),
18: sub(18, "Di Ambang Generator",
 "Kain yang Kembali", [
 ("18B.1a", "Close-Up", "Benang jaring termal tertarik kembali dan menenun ulang kain sarung di pinggang Gala.", "Close-up: the glowing thermal-net threads retract and weave themselves back into the batik sash at Gala's waist.", "G"),
 ("18B.1b", "Medium Shot", "Gala mengencangkan simpul; kain sarung utuh kembali.", "Gala tightens the knot of his fully restored batik sash.", "G"),
 ("18B.1c", "Close-Up", "Aila membobol panel alarm pintu; layar retak berubah hijau.", "Close-up: Aila bypasses the door's alarm panel; the ice-cracked screen turns green.", "A"),
 ("18B.1d", "Action Shot", "Dhruva menahan perisai di pintu raksasa, mendorongnya terbuka perlahan.", "Dhruva braces his shield against the massive generator door, pushing it open inch by inch.", "D"),
 ],
 "Tiga Anjungan", [
 ("18B.2a", "Wide Shot", "Pintu terbuka; cahaya biru membanjir; kristal raksasa berputar di baliknya.", "The door grinds open; blue light floods out over the squad, a giant spinning crystal visible beyond.", "GAD"),
 ("18B.2b", "Medium Shot", "Gala memberi isyarat: Aila dan Dhruva ke anjungan samping.", "Gala signals Aila and Dhruva to take the side catwalks.", "GAD"),
 ("18B.2c", "Wide Shot", "Regu berpencar di tiga anjungan mengelilingi generator.", "The squad splits across three catwalks circling the spinning generator crystal.", "GAD"),
 ("18B.2d", "Close-Up", "Bayangan jatuh dari atas ke anjungan Gala; es merambat.", "A dark shadow drops from above onto Gala's catwalk, frost racing across the metal toward him.", "G"),
 ]),
19: sub(19, "Pesan Sang Komandan",
 "Protokol Pembekuan", [
 ("19B.1a", "Close-Up", "Himakara, zirah retak, menyeringai di balik helm pecah.", "Close-up: Commander Himakara, armor cracked, smirks under his shattered helmet.", ""),
 ("19B.1b", "Medium Shot", "Gala berlutut menodongkan gauntlet menyala ke arahnya.", "Gala kneels over him, a glowing gauntlet held ready.", "G"),
 ("19B.1c", "Close-Up", "Himakara mengetuk pergelangan; hologram kota membeku: 'PROTOCOL: CITYWIDE FREEZE'.", "Close-up: Himakara taps his wrist; a hologram of a city grid icing over appears with the text 'PROTOCOL: CITYWIDE FREEZE'.", ""),
 ("19B.1d", "Wide Shot", "Himakara pecah menjadi embun beku dan lenyap.", "Himakara shatters into frost dust and vanishes as Gala recoils.", "G"),
 ],
 "Bala Bantuan Musuh", [
 ("19B.2a", "Wide Shot", "Cryo-Guard menyerbu dari dua pintu samping.", "Cryo-Guards pour through both side entrances of the generator room.", ""),
 ("19B.2b", "Action Shot", "Dhruva menahan gerbang kiri dengan perisainya.", "Dhruva holds the left gate alone, shield braced against a wall of guards.", "D"),
 ("19B.2c", "Action Shot", "Aila menutup gerbang kanan dengan dinding angin menderu.", "Aila seals the right gate with a howling wall of wind.", "A"),
 ("19B.2d", "Medium Shot", "Gala berbalik ke arah kristal: saatnya mengakhiri ini.", "Gala turns toward the spinning crystal core with grim resolve.", "G"),
 ]),
20: sub(20, "Kabar dari Kota",
 "Penerbangan Pulang", [
 ("20B.1a", "Medium Interior Shot", "Regu beristirahat di kapal; Dhruva tertidur bersandar pada perisainya.", "Inside the transport the squad rests; Dhruva dozes against his shield while Gala and Aila sit nearby.", "GAD"),
 ("20B.1b", "Close-Up", "Aila memutar ulang hologram 'PROTOCOL: CITYWIDE FREEZE' di visornya, cemas.", "Close-up: Aila replays the 'PROTOCOL: CITYWIDE FREEZE' hologram on her visor, worried.", "A"),
 ("20B.1c", "Medium Shot", "Gala mempelajarinya; Ethylene meredup gelisah.", "Gala studies the hologram, the sprite dimming uneasily beside him.", "GS"),
 ("20B.1d", "Wide Shot", "Kapal melintasi pegunungan menuju lampu kota saat senja.", "The transport crosses the mountains toward distant city lights at dusk.", ""),
 ],
 "Lampu yang Padam", [
 ("20B.2a", "Wide Shot", "Di kejauhan, satu distrik kota padam.", "In the distance, one whole district of the city blinks into darkness.", ""),
 ("20B.2b", "First-Person POV (HUD)", "HUD: 'CITY GRID FAILURE - 3 DISTRICTS OFFLINE'.", "First-person HUD alert 'CITY GRID FAILURE - 3 DISTRICTS OFFLINE' over the darkening skyline.", ""),
 ("20B.2c", "Medium Shot", "Gala berdiri memegang pegangan atas kapal; kain sarung berkibar.", "Gala stands and grips the overhead rail, his sash swaying with the ship.", "G"),
 ("20B.2d", "Title Card", "Kapal berbelok ke kota yang menggelap: 'OPERATION ICEBOUND PEAK: COMPLETE'.", "The transport banks toward the darkening city; title card 'OPERATION ICEBOUND PEAK: COMPLETE'.", ""),
 ]),
21: sub(21, "Kota yang Menggigil",
 "Turun dari Rel", [
 ("21B.1a", "Wide Shot", "Aila menurunkan penumpang satu per satu dengan bantalan angin.", "Aila lowers monorail passengers one by one to the street on a soft cushion of wind.", "A"),
 ("21B.1b", "Medium Shot", "Dhruva menangkap seorang anak di bawah dan menyelimutinya.", "Dhruva catches a small child at the bottom and wraps him in a thermal blanket.", "D"),
 ("21B.1c", "Medium Shot", "Gala menahan perisai di bawah monorail sampai penumpang terakhir turun.", "Gala holds his batik shield under the monorail until the last passenger is down.", "G"),
 ("21B.1d", "Wide Shot", "Monorail diturunkan perlahan ke rel; perisai memudar.", "The monorail settles gently back onto its track as Gala's shield fades.", "G"),
 ],
 "Panggilan Rumah Sakit", [
 ("21B.2a", "First-Person POV (HUD)", "HUD: 'CITY HOSPITAL - BACKUP POWER: 6 MIN'.", "First-person HUD alert 'CITY HOSPITAL - BACKUP POWER: 6 MIN' with a map pin.", ""),
 ("21B.2b", "Medium Shot", "Gala membagi tugas: Aila dan Dhruva menjaga warga di stasiun.", "Gala assigns Aila and Dhruva to guard the crowd at the station.", "GAD"),
 ("21B.2c", "Aerial Shot", "Gala terbang di atas jalan gelap menuju rumah sakit.", "Aerial: Gala flies over dark icy streets toward a hospital with one red emergency light.", "G"),
 ("21B.2d", "Wide Shot", "Gala mendarat di pintu rumah sakit; perawat melambai panik.", "Gala lands at the hospital entrance where nurses wave to him frantically.", "G"),
 ]),
22: sub(22, "Baterai Harapan",
 "Mengisi Penuh", [
 ("22B.1a", "Medium Shot", "Di ruang bawah tanah, kain sarung Gala tersambung ke deretan sel baterai.", "In the hospital basement, Gala's batik sash is plugged into a long row of battery cells.", "G"),
 ("22B.1b", "Close-Up", "Indikator baterai naik ke 100%, berwarna emas.", "Close-up: a battery gauge climbing to 100% in bright gold.", ""),
 ("22B.1c", "Close-Up", "Gala mencabut kain sarung dan limbung; Ethylene menopang pipinya.", "Gala unplugs his sash and sways with fatigue; the sprite presses against his cheek to steady him.", "GS"),
 ("22B.1d", "Medium Shot", "Seorang dokter berterima kasih dengan membungkuk kecil.", "A doctor thanks Gala with a small bow in the corridor.", "G"),
 ],
 "Dua Sinyal", [
 ("22B.2a", "Medium Shot", "Aila dan Dhruva tiba di atap rumah sakit; regu berkumpul kembali.", "Aila and Dhruva land on the hospital rooftop, regrouping with Gala.", "GAD"),
 ("22B.2b", "Medium Shot", "Peta kota membeku terproyeksi; dua zona merah menyala di utara dan selatan.", "A frosted city map projects between the three of them, two red zones flaring in the north and south.", "GAD"),
 ("22B.2c", "Close-Up", "Rahang Gala mengeras; ia berpikir cepat.", "Close-up: Gala's jaw sets as he thinks fast, the red zones reflected on his lenses.", "G"),
 ("22B.2d", "Wide Shot", "Ketiganya menatap dua kepulan es biru di kejauhan.", "The three look across the frozen skyline at two plumes of blue frost rising far apart.", "GAD"),
 ]),
23: sub(23, "Menara yang Membeku",
 "Kembali Berkumpul", [
 ("23B.1a", "Medium Shot", "Aila dan Dhruva mendarat di kilang gas, lecet tempur; perisai Dhruva berembun.", "Aila and Dhruva land at the gas plant, battle-scuffed, Dhruva's shield frosted over.", "AD"),
 ("23B.1b", "Medium Shot", "Gala nyengir dan beradu lengan dengan Dhruva.", "Gala grins and bumps forearms with Dhruva.", "GD"),
 ("23B.1c", "Wide Shot", "Lampu distrik di sekitar kilang menyala kembali.", "District lights around the gas plant blink back on one block at a time.", ""),
 ("23B.1d", "Close-Up", "Ethylene berputar gembira di atas kepala ketiganya.", "Close-up: the sprite spins happily in the air above the three squadmates' heads.", "GSAD"),
 ],
 "Sosok di Puncak", [
 ("23B.2a", "Wide Shot", "Di seberang kota, Monumen Atom dirayapi es biru.", "Across the city, the atomic spire monument is crawling with blue ice from base to peak.", ""),
 ("23B.2b", "First-Person POV (HUD)", "HUD memperbesar siluet bersayap di puncak: 'ID: COMMANDER FROSTWING'.", "First-person HUD zooms on a winged silhouette at the spire tip: 'ID: COMMANDER FROSTWING'.", ""),
 ("23B.2c", "Medium Shot", "Gala memerintahkan regu membersihkan drone di kaki menara; ia naik sendiri.", "Gala orders Aila and Dhruva to clear the drones at the monument's base while he goes up.", "GAD"),
 ("23B.2d", "Low Angle Shot", "Gala berjongkok, pendorong boots menyala, menatap menara.", "Low angle: Gala crouches, boot thrusters igniting, looking up at the frozen spire.", "G"),
 ]),
24: sub(24, "Meriam yang Masih Berdetak",
 "Tembakan Otomatis", [
 ("24B.1a", "Close-Up", "Meriam beku yang ditinggalkan di puncak masih mengisi daya.", "Close-up: the abandoned frost cannon on the spire peak is still charging, a blue ring filling up.", ""),
 ("24B.1b", "First-Person POV (HUD)", "HUD: 'AUTO-FIRE IN 20 SECONDS'.", "First-person HUD countdown 'AUTO-FIRE IN 20 SECONDS' locked on the cannon.", ""),
 ("24B.1c", "Action Shot", "Gala membelokkan laras meriam ke langit dengan kedua gauntlet.", "Gala wrenches the heavy cannon barrel skyward with both gauntlets, straining.", "G"),
 ("24B.1d", "Wide Shot", "Meriam menembak ke awan; cincin es menyebar di langit tanpa bahaya.", "The cannon fires harmlessly into the clouds, a vast ring of frost spreading across the sky above Gala.", "G"),
 ],
 "Soket Inti Menara", [
 ("24B.2a", "Action Shot", "Aila naik dengan arus angin dan mendarat di samping Gala.", "Aila rides an updraft to the peak and lands beside Gala.", "GA"),
 ("24B.2b", "Medium Shot", "Dhruva melapor dari bawah sambil menahan drone dengan perisai.", "At the monument's base, Dhruva holds back drones with his shield while calling up on comms.", "D"),
 ("24B.2c", "Close-Up", "Gala mencongkel panel beku, memperlihatkan soket inti yang bercahaya.", "Close-up: Gala pries off a frozen maintenance panel, revealing the glowing core socket.", "G"),
 ("24B.2d", "Medium Shot", "Gala dan Aila saling mengangguk; Gala meregangkan gauntlet di atas soket.", "Gala and Aila exchange a nod; Gala flexes his gauntlets above the socket.", "GA"),
 ]),
25: sub(25, "Menuju Lembah Hitam",
 "Rencana Serangan", [
 ("25B.1a", "Wide Shot", "War room; hologram citadel melayang; Komandan dan regu berkumpul.", "In the war room, a hologram of the dark citadel floats over the table; the Commander and the squad gather around.", "GAD"),
 ("25B.1b", "Close-Up", "Hologram menunjukkan lapisan perisai antimateri citadel.", "Close-up: the hologram peels apart the citadel's layered anti-matter shields.", ""),
 ("25B.1c", "Medium Shot", "Komandan menyerahkan slate misi kepada Gala.", "The Commander hands Gala a glowing mission slate.", "G"),
 ("25B.1d", "Medium Shot", "Regu bersiap di hanggar: Dhruva mengencangkan tali perisai, Aila mengkalibrasi visor.", "In the hangar, Dhruva tightens his shield straps and Aila calibrates her visor.", "AD"),
 ],
 "Malam Sebelum Penyerbuan", [
 ("25B.2a", "Wide Shot", "Malam; kota yang pulih bersinar di bawah Monumen Atom.", "Night: the restored city glows warmly below the atomic monument.", ""),
 ("25B.2b", "Medium Shot", "Gala dan regu duduk di tepi platform menara, kaki menjuntai.", "Gala, Aila and Dhruva sit on the edge of the monument platform, legs dangling over the city.", "GAD"),
 ("25B.2c", "Close-Up", "Ethylene beristirahat di telapak Gala, apinya tenang.", "Close-up: the sprite rests in Gala's palm, its flame calm and steady.", "GS"),
 ("25B.2d", "Title Card", "Siluet Gala dan Ethylene di menara: 'ARC 2 COMPLETE - CITYWIDE POWER RESTORED'.", "Gala and the sprite silhouetted on the monument above the glowing city; title card 'ARC 2 COMPLETE - CITYWIDE POWER RESTORED'.", "GS"),
 ]),
26: sub(26, "Aula Pertama",
 "Barisan Penjaga", [
 ("26B.1a", "Wide Shot", "Barisan Cryo-Guard memenuhi aula agung yang gelap.", "Rows of Cryo-Guards fill the grand dark crystal hall.", ""),
 ("26B.1b", "Action Shot", "Dhruva memimpin terjangan perisai, menjatuhkan penjaga.", "Dhruva leads a shield charge that bowls the first line of guards over.", "D"),
 ("26B.1c", "Action Shot", "Tornado Aila mengangkat penjaga dan menjatuhkannya.", "Aila's tornado lifts a group of guards off their feet and drops them.", "A"),
 ("26B.1d", "Action Shot", "Gala melompati keduanya dan menendang barisan terakhir.", "Gala leaps over both teammates and lands a flaming kick on the last line of guards.", "G"),
 ],
 "Suara dari Singgasana", [
 ("26B.2a", "Wide Shot", "Dinding kristal berdenyut biru gelap; suara berat menggema.", "The crystal walls pulse dark blue as a deep voice echoes through the hall.", ""),
 ("26B.2b", "Close-Up", "Lensa Gala memantulkan wajah es raksasa yang terbentuk di dinding.", "Close-up: Gala's lenses reflect a giant icy face forming in the crystal wall.", "G"),
 ("26B.2c", "Medium Shot", "Regu merapat, saling membelakangi.", "The squad closes into a tight formation, backs together.", "GAD"),
 ("26B.2d", "Wide Shot", "Pintu terbuka ke aula berlantai kristal dengan garis biru samar.", "A door slides open onto a hall with a crystal floor, faint blue lines glowing beneath it.", "GAD"),
 ]),
27: sub(27, "Yang Harus Tinggal",
 "Mencairkan Regu", [
 ("27B.1a", "Wide Shot", "Aula yang mencair; Aila dan Dhruva masih terbungkus es tipis.", "In the melting hall, Aila and Dhruva are still encased in thinning shells of ice.", "AD"),
 ("27B.1b", "Close-Up", "Gauntlet Gala di es sekitar Dhruva; es retak terbuka.", "Close-up: Gala's gauntlet on the ice around Dhruva; it cracks open.", "GD"),
 ("27B.1c", "Medium Shot", "Dhruva terhuyung keluar; satu kakinya masih membeku, tak bisa berdiri.", "Dhruva stumbles free, one leg still crusted with frost, unable to stand.", "D"),
 ("27B.1d", "Close-Up", "Aila berlutut di sampingnya; visornya menampilkan status Dhruva.", "Aila kneels beside Dhruva, her visor displaying his vital readings.", "AD"),
 ],
 "Pergi Sendiri", [
 ("27B.2a", "Medium Shot", "Aila menyuruh Gala pergi; ia akan menjaga aula bersama Dhruva.", "Aila tells Gala to go on; she will hold the hall with Dhruva.", "GA"),
 ("27B.2b", "Close-Up", "Dhruva menegakkan perisainya, nyengir menahan sakit.", "Close-up: Dhruva slams his shield upright beside him, grinning through the pain.", "D"),
 ("27B.2c", "Medium Shot", "Gala memberi hormat Galians kepada mereka, kepalan di dada.", "Gala places his fist over his chest in the Galians salute to his teammates.", "G"),
 ("27B.2d", "Wide Shot", "Gala mendorong pintu singgasana raksasa sendirian; cahaya dingin tumpah keluar.", "Gala pushes open the giant throne-room door alone, cold light spilling out; the sprite at his shoulder.", "GS"),
 ]),
28: sub(28, "Penguasa Nol Mutlak",
 "Pukulan Pertama", [
 ("28B.1a", "Wide Shot", "Lord menuruni tangga singgasana; tiap langkah membekukan lantai.", "Lord Absolute Zero descends the throne stairs, each step freezing the floor around his boots.", ""),
 ("28B.1b", "Action Shot", "Lord menampar Gala dengan gauntlet es hingga terlempar.", "Lord Absolute Zero backhands Gala with an ice gauntlet, sending him flying across the room.", "G"),
 ("28B.1c", "Close-Up", "Gala terbatuk, zirah berembun, mendorong tubuhnya bangkit.", "Close-up: Gala coughs, armor frosted, pushing himself up from the floor.", "G"),
 ("28B.1d", "Medium Action Shot", "Pukulan api beruntun Gala nyaris tak menggores zirah Lord.", "Gala answers with rapid flaming punches that barely chip the Lord's spiked armor.", "G"),
 ],
 "Peringatan HUD", [
 ("28B.2a", "Close-Up", "Orb antimateri berputar di telapak Lord, ruang melengkung di sekitarnya.", "Close-up: the anti-matter orb spinning in the Lord's palm, space visibly warping around it.", ""),
 ("28B.2b", "First-Person POV (Warning)", "HUD: 'WARNING: HIGH-ENERGY COLLISION MAY BREACH SPACE-TIME'.", "First-person HUD warning 'WARNING: HIGH-ENERGY COLLISION MAY BREACH SPACE-TIME' over the orb.", ""),
 ("28B.2c", "Close-Up", "Mulut Gala menegang ragu; Ethylene menatapnya.", "Close-up: Gala's mouth tightens in hesitation; the sprite looks up at him.", "GS"),
 ("28B.2d", "Low Angle Shot", "Gala tetap memantapkan kuda-kuda; batik menyala terang.", "Low angle: Gala sets his stance anyway, the gold batik on his armor flaring bright.", "G"),
 ]),
29: sub(29, "Runtuhnya Citadel",
 "Jejak Ungu", [
 ("29B.1a", "Close-Up", "Di titik ledakan orb, retakan ungu-perak kecil menggantung di udara.", "Close-up: where the orb exploded, a tiny purple-silver crack hangs in mid-air, flickering.", ""),
 ("29B.1b", "Medium Shot", "Gala menatapnya; HUD glitch.", "Gala stares at the crack, his goggle lenses glitching with purple static.", "G"),
 ("29B.1c", "Wide Shot", "Retakan lenyap saat langit-langit runtuh.", "The crack winks out as chunks of the ceiling come crashing down.", ""),
 ("29B.1d", "Action Shot", "Gala berlari keluar singgasana menembus reruntuhan es.", "Gala sprints out of the throne room through falling ice.", "G"),
 ],
 "Keluar Bersama", [
 ("29B.2a", "Wide Shot", "Gala tiba di aula; Aila memapah Dhruva.", "Gala reaches the hall where Aila is holding Dhruva up.", "GAD"),
 ("29B.2b", "Action Shot", "Gala memapah lengan Dhruva yang lain; ketiganya berlari.", "Gala takes Dhruva's other arm and the three run together.", "GAD"),
 ("29B.2c", "Wide Shot", "Kapal angkut melayang di dinding yang jebol, ramp terbuka.", "A Galians transport hovers at a broken wall opening, its ramp down.", ""),
 ("29B.2d", "Action Shot", "Regu melompat ke ramp saat aula runtuh di belakang.", "The squad leaps onto the ramp as the hall collapses behind them.", "GAD"),
 ]),
30: sub(30, "Langit yang Terbelah",
 "Regu di Bawah Retakan", [
 ("30B.1a", "Wide Shot", "Aila dan Dhruva (kaki dibalut) menyusul Gala di alun-alun di bawah retakan.", "Aila and Dhruva, his leg bandaged, join Gala in the plaza beneath the glowing rift.", "GAD"),
 ("30B.1b", "Close-Up", "Ethylene berkedip tak menentu, ketakutan di dekat retakan.", "Close-up: the sprite flickers erratically near the rift, frightened.", "S"),
 ("30B.1c", "First-Person POV (HUD)", "HUD: jam di dekat retakan tidak sinkron '23:14:07 / 23:13:52'.", "First-person HUD showing two mismatched clocks near the rift: '23:14:07 / 23:13:52'.", ""),
 ("30B.1d", "Medium Shot", "Aila melirik Gala: itu titik tabrakan orb; wajah Gala merasa bersalah.", "Aila glances at Gala as she realizes where the rift came from; Gala lowers his head, guilty.", "GA"),
 ],
 "Bayangan Kota Lain", [
 ("30B.2a", "Low Angle Shot", "Di balik retakan, cakrawala kota yang sama, gelap dan membeku.", "Low angle: through the rift, a mirrored skyline of the same city appears, dark and frozen.", ""),
 ("30B.2b", "Close-Up", "Gala mengenali Monumen Atom di kota cermin itu, mati dan berlapis es.", "Close-up: Gala recognizes the atomic monument in the mirrored city, dead and iced over, reflected in his lenses.", "G"),
 ("30B.2c", "Medium Shot", "Gala mengepalkan tangan; Ethylene di bahunya; regu di sampingnya.", "Gala clenches his fist, the sprite settling on his shoulder, Aila and Dhruva beside him.", "GSAD"),
 ("30B.2d", "Title Card", "'SEASON 2 COMPLETE'.", "The squad silhouetted beneath the purple-silver rift; title card 'SEASON 2 COMPLETE'.", "GSAD"),
 ]),
}
